---
# How to run this playbook:
# 0 List hosts:         ansible-playbook -vvv -i inventory/hosts -l [hostname|hostgrp] --list-hosts install_puppet_master.yaml
# 1 Syntax check:       ansible-playbook -vvv -i inventory/hosts -l [hostname|hostgrp] --syntax-check install_puppet_master.yaml
# 2.1 Dry-Run playbook: ansible-playbook -vvv -i inventory/hosts -l [hostname|hostgrp] -C install_puppet_master.yaml -K
# 2.2 Dry-Run tasks:    ansible-playbook -vvv -i inventory/hosts -l [hostname|hostgrp] install_puppet_master.yaml -K
#  set check_mode: yes for selected tasks
# 3 Actual-Run tasks:   ansible-playbook -vvv -i inventory/hosts -l [hostname|hostgrp] install_puppet_master.yaml -K
#  set check_mode: no for selected tasks
# 4 Actual-Run playbook: ansible-playbook -vv -i inventory/hosts -l [hostname|hostgrp] install_puppet_master.yaml -K

# Pre-requisites: 
# 1. Ubuntu or RHEL Linux for remote host
# 2. run_user@controller_host SSH key trusted by remote_user@remote_host, mode 700 for .ssh, mode 640 for authorized_keys
# 3. Make sure remote host IP is in DNS or /etc/hosts, otherwise `hostname -i` returns undesired multiple entries

# Assumptions: 
# 1. OS for Puppet Master is Ubuntu 18.04 (as of 6-May-2021 20.04 is not listed) or RHEL 8.X

- name: Install/Re-Install Puppet Enterprise 2021.4 Primary Master and PDK 2.2.0
  hosts: all
  become: yes
  gather_facts: no
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"
    PPM_IP: "192.168.159.128"
    PPM_FQDN: "puppet.example.local"
    PPM_SHORT: "puppet" 
  vars_prompt:
    - name: ADMIN_PASSWORD
      prompt: The Puppet Primary Master Admin Password
  tasks:
    - name: Ensure Puppet FQDN is in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ PPM_IP }} {{ PPM_FQDN }} {{ PPM_SHORT }}"
    - name: Firewall Rules - http, https, puppetserver 8140/tcp 
      shell: |
        firewall-cmd --add-service={http,https} --permanent
        firewall-cmd --add-port=8140/tcp --permanent
        firewall-cmd --reload
        firewall-cmd --list-services
        firewall-cmd --list-ports
      register: output
    - debug:
        var: output
    - name: Install PE Primary Master and PDK
      shell: |
        cd /tmp
        which apt-get
        if [ $? -eq 0 ]; then
          apt-get install -y curl
          # Update GPG Key
          curl --remote-name --location https://apt.puppet.com/DEB-GPG-KEY-puppet-20250406
          gpg --keyid-format 0xLONG --with-fingerprint ./DEB-GPG-KEY-puppet-20250406
          apt-key add DEB-GPG-KEY-puppet-20250406
          # Downloads
          rm -f puppet-enterprise-2021.4.0-ubuntu-18.04-amd64.tar.gz pdk_2.3.0.0-1focal_amd64.deb
          curl -JLO 'https://pm.puppet.com/cgi-bin/download.cgi?dist=ubuntu&rel=18.04&arch=amd64&ver=latest' || true
          curl -JLO 'https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=20.04&arch=amd64&ver=latest' || true
          # Install
          apt-get update
          dpkg -i pdk_2.3.0.0-1focal_amd64.deb || true
          tar -zxf puppet-enterprise-2021.4.0-ubuntu-18.04-amd64.tar.gz
          cd puppet-enterprise-2021.4.0-ubuntu-18.04-amd64
          bash ./puppet-enterprise-installer -c conf.d/pe.conf
        else
          set enforce 0
          sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config
          yum install -y curl
          # Update GPG Key
          curl --remote-name --location https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406
          gpg --keyid-format 0xLONG --with-fingerprint ./RPM-GPG-KEY-puppet-20250406
          rpm --import RPM-GPG-KEY-puppet-20250406
          # Downloads
          rm -f puppet-enterprise-2021.4.0-el-8-x86_64.tar.gz pdk-2.3.0.0-1.el8.x86_64.rpm
          curl -JLO 'https://pm.puppet.com/cgi-bin/download.cgi?dist=el&rel=8&arch=x86_64&ver=latest' || true
          curl -JLO 'https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=el&rel=8&arch=x86_64&ver=latest' || true
          # Install
          yum update
          yum install -y pdk-2.3.0.0-1.el8.x86_64.rpm || true
          tar -zxf puppet-enterprise-2021.4.0-el-8-x86_64.tar.gz
          cd puppet-enterprise-2021.4.0-el-8-x86_64
          bash ./puppet-enterprise-installer -c conf.d/pe.conf
        fi
      register: output
      ignore_errors: yes
    - debug:
        var: output
    - name: Enable and Start Puppet Agent
      systemd:
        name: puppet
        enabled: yes
        state: restarted
      ignore_errors: yes
      register: output
    - debug:
        var: output
    - name: Ensure PE Puppet and PDK binaries in $PATH in ~root/.bashrc
      lineinfile:
        path: /root/.bashrc
        line: "export PATH=$PATH:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin"
    - name: Set Puppet Admin Password
      shell: ". /root/.bashrc; /opt/puppetlabs/puppet/bin/puppet infrastructure console_password --password={{ ADMIN_PASSWORD }}"
      ignore_errors: yes
      no_log: yes
  

